services:
  - type: web
    name: blog-platform-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blog_platform.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog_platform.settings
